package example

import (
	"context"
	_ "embed"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazerolift"
)

// addWasm was generated by the following:
//
//	wasm-tools parse testdata/add.wat -o testdata/add.wasm
//
//go:embed testdata/add.wasm
var addWasm []byte

func TestExample(t *testing.T) {
	config := wazero.NewRuntimeConfig()
	wazerolift.ConfigureCranelift(config)
	ctx := context.Background()
	r := wazero.NewRuntimeWithConfig(ctx, config)
	inst, err := r.InstantiateModuleFromBinary(ctx, addWasm)
	require.NoError(t, err)

	add := inst.ExportedFunction("add")
	require.NotNil(t, add)

	result, err := add.Call(ctx, 1, 2)
	require.NoError(t, err)
	require.Equal(t, uint64(3), result[0])
}
